name: Java Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Check Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test -Dsurefire.suiteXmlFiles=testing.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test Results
        path: target/surefire-reports
